### ISSUE TITLE
Categorize textures by mod name

### ISSUE THREAD

**Issue by tacotexmex** [zayuim/IsabellaTest#1]
In 5.0.0 it’s possible to sort textures in subdirectories. This makes it much more navigable. Have a look at the 0.5.0-dev branch of GMC for an example.

**Comment by ghost** [comment]
I would like to get into this! Are you currently doing this on your PixelPerfection port?

**Comment by tacotexmex** [comment]
Yes, and I’ve merged that version now with MT 5 being released. Just look at my structure for an example.

**Comment by ghost** [comment]
@tacotexmex  OK, I've done it. You are free to look over and close if you are happy.

**Comment by tacotexmex** [comment]
Directory structure looks good but now you have duplicates of the textures, both in directory and in root…

**Comment by ghost** [comment]
OK, I have fixed the issue. I misunderstood git, I though it would delete the files out of the root, if I moved them :)

**Comment by tacotexmex** [comment]
Good, though now you yanked screenshot.png too.
